@startuml
class Usuario {
    -login: String
    -senha: String
    +realizarLogin(login: String, senha: String): boolean
}

class Aluno {
    -matricula: String
    -nome: String
    +matricularEmDisciplina(disciplina: Disciplina): boolean
    +cancelarMatricula(disciplina: Disciplina): boolean
    +buscarDisciplina(nome: String): Disciplina
}

class Professor {
    -nome: String
    +consultarAlunosPorDisciplina(disciplina: Disciplina): List<Aluno>
}

class Secretaria {
    +gerarCurriculo(aluno: Aluno): void
    +notificarSistemaFinanceiro(aluno: Aluno): void
}

class Disciplina {
    -nome: String
    -creditos: int
    -alunosMatriculados: List<Aluno>
    +matricularAluno(aluno: Aluno): boolean
    +cancelarMatricula(aluno: Aluno): boolean
    +getAlunosMatriculados(): List<Aluno>
}



Usuario <|-- Aluno
Usuario <|-- Professor
Usuario <|-- Secretaria

Aluno --> Disciplina : matricular
Aluno --> Secretaria : solicitarCurriculo
Aluno --> Disciplina : buscar
Professor --> Disciplina : consultarAlunos
Secretaria --> Aluno : geraCurriculo
@enduml
