@startuml
left to right direction

' Define os atores
actor Aluno
actor Professor
actor Secretaria
actor Usuario

Aluno--|> Usuario
Professor--|> Usuario
Secretaria--|> Usuario


' Define os casos de uso
usecase "Gerar Currículo" as UC1
usecase "Consultar Alunos por Disciplina" as UC2
usecase "Matricular em Disciplina" as UC3
usecase "Cancelar Matrícula" as UC4
usecase "Realizar login" as UC6
usecase "Buscar disciplina" as UC7
usecase "Notificar sistema financeiro" as UC8

' Define as relações entre atores e casos de uso

Usuario --> UC6

Aluno --> UC4
Aluno --> UC3
UC3 --> Secretaria
UC8 ..> UC3 : <<includ>>

Aluno --> UC7
UC4 ..> UC3 : <<extend>>
UC3 ..> UC7 : <<includ>>

Professor --> UC2 

Secretaria --> UC1
UC1 --> Aluno
@enduml