@startuml
' Define os atores
actor Aluno
actor Professor
actor Secretaria
actor SistemaCobranças as "Tesouraria"
actor Usuario

Aluno--|> Usuario
Professor--|> Usuario
Secretaria--|> Usuario
Tesouraria--|> Usuario

' Define os casos de uso
usecase "Gerar Currículo" as UC1
usecase "Consultar Alunos por Disciplina" as UC2
usecase "Matricular em Disciplina" as UC3
usecase "Cancelar Matrícula" as UC4
usecase "Gerar Cobrança" as UC5
usecase "Realizar login" as UC6


' Define as relações entre atores e casos de uso

Usuario --> UC6

Aluno --> UC3 


UC4 ..> UC3

Professor --> UC2 

Secretaria --> UC1
UC1 --> Aluno

SistemaCobranças --> UC5
UC5 --> Aluno
Secretaria--> UC3
@enduml

Sistema --> UC6 : "Valida login"
Sistema --> UC3 : "Permite matrícula"
Sistema --> UC4 : "Permite cancelamento"

@enduml
